/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseRouteImport } from './routes/why-choose'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorsIndexRouteImport } from './routes/sectors.index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as SectorsSectorIdRouteImport } from './routes/sectors.$sectorId'
import { Route as ProductsAccessControlRouteImport } from './routes/products_.access-control'
import { Route as ProductsAccessControlSaltoRouteImport } from './routes/products_.access-control_.salto'
import { Route as ProductsAccessControlHoneywellRouteImport } from './routes/products_.access-control_.honeywell'
import { Route as ProductsAccessControlSaltoProductIdRouteImport } from './routes/products_.access-control_.salto_.$productId'
import { Route as ProductsAccessControlHoneywellUpgradesRouteImport } from './routes/products_.access-control_.honeywell_.upgrades'
import { Route as ProductsAccessControlHoneywellSoftwareRouteImport } from './routes/products_.access-control_.honeywell_.software'
import { Route as ProductsAccessControlHoneywellReadersRouteImport } from './routes/products_.access-control_.honeywell_.readers'
import { Route as ProductsAccessControlHoneywellLobbyKiosksRouteImport } from './routes/products_.access-control_.honeywell_.lobby-kiosks'
import { Route as ProductsAccessControlHoneywellDoorHardwareRouteImport } from './routes/products_.access-control_.honeywell_.door-hardware'
import { Route as ProductsAccessControlHoneywellCredentialsRouteImport } from './routes/products_.access-control_.honeywell_.credentials'
import { Route as ProductsAccessControlHoneywellControlPanelsRouteImport } from './routes/products_.access-control_.honeywell_.control-panels'
import { Route as ProductsAccessControlHoneywellControlPanelKitsRouteImport } from './routes/products_.access-control_.honeywell_.control-panel-kits'
import { Route as ProductsAccessControlHoneywellAccessoriesRouteImport } from './routes/products_.access-control_.honeywell_.accessories'

const WhyChooseRoute = WhyChooseRouteImport.update({
  id: '/why-choose',
  path: '/why-choose',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SectorsRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSectorIdRoute = SectorsSectorIdRouteImport.update({
  id: '/$sectorId',
  path: '/$sectorId',
  getParentRoute: () => SectorsRoute,
} as any)
const ProductsAccessControlRoute = ProductsAccessControlRouteImport.update({
  id: '/products_/access-control',
  path: '/products/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAccessControlSaltoRoute =
  ProductsAccessControlSaltoRouteImport.update({
    id: '/products_/access-control_/salto',
    path: '/products/access-control/salto',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellRoute =
  ProductsAccessControlHoneywellRouteImport.update({
    id: '/products_/access-control_/honeywell',
    path: '/products/access-control/honeywell',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlSaltoProductIdRoute =
  ProductsAccessControlSaltoProductIdRouteImport.update({
    id: '/products_/access-control_/salto_/$productId',
    path: '/products/access-control/salto/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellUpgradesRoute =
  ProductsAccessControlHoneywellUpgradesRouteImport.update({
    id: '/products_/access-control_/honeywell_/upgrades',
    path: '/products/access-control/honeywell/upgrades',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellSoftwareRoute =
  ProductsAccessControlHoneywellSoftwareRouteImport.update({
    id: '/products_/access-control_/honeywell_/software',
    path: '/products/access-control/honeywell/software',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellReadersRoute =
  ProductsAccessControlHoneywellReadersRouteImport.update({
    id: '/products_/access-control_/honeywell_/readers',
    path: '/products/access-control/honeywell/readers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellLobbyKiosksRoute =
  ProductsAccessControlHoneywellLobbyKiosksRouteImport.update({
    id: '/products_/access-control_/honeywell_/lobby-kiosks',
    path: '/products/access-control/honeywell/lobby-kiosks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellDoorHardwareRoute =
  ProductsAccessControlHoneywellDoorHardwareRouteImport.update({
    id: '/products_/access-control_/honeywell_/door-hardware',
    path: '/products/access-control/honeywell/door-hardware',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellCredentialsRoute =
  ProductsAccessControlHoneywellCredentialsRouteImport.update({
    id: '/products_/access-control_/honeywell_/credentials',
    path: '/products/access-control/honeywell/credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellControlPanelsRoute =
  ProductsAccessControlHoneywellControlPanelsRouteImport.update({
    id: '/products_/access-control_/honeywell_/control-panels',
    path: '/products/access-control/honeywell/control-panels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellControlPanelKitsRoute =
  ProductsAccessControlHoneywellControlPanelKitsRouteImport.update({
    id: '/products_/access-control_/honeywell_/control-panel-kits',
    path: '/products/access-control/honeywell/control-panel-kits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsAccessControlHoneywellAccessoriesRoute =
  ProductsAccessControlHoneywellAccessoriesRouteImport.update({
    id: '/products_/access-control_/honeywell_/accessories',
    path: '/products/access-control/honeywell/accessories',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/services': typeof ServicesRoute
  '/why-choose': typeof WhyChooseRoute
  '/products/access-control': typeof ProductsAccessControlRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
  '/about/': typeof AboutIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/products/access-control/honeywell': typeof ProductsAccessControlHoneywellRoute
  '/products/access-control/salto': typeof ProductsAccessControlSaltoRoute
  '/products/access-control/honeywell/accessories': typeof ProductsAccessControlHoneywellAccessoriesRoute
  '/products/access-control/honeywell/control-panel-kits': typeof ProductsAccessControlHoneywellControlPanelKitsRoute
  '/products/access-control/honeywell/control-panels': typeof ProductsAccessControlHoneywellControlPanelsRoute
  '/products/access-control/honeywell/credentials': typeof ProductsAccessControlHoneywellCredentialsRoute
  '/products/access-control/honeywell/door-hardware': typeof ProductsAccessControlHoneywellDoorHardwareRoute
  '/products/access-control/honeywell/lobby-kiosks': typeof ProductsAccessControlHoneywellLobbyKiosksRoute
  '/products/access-control/honeywell/readers': typeof ProductsAccessControlHoneywellReadersRoute
  '/products/access-control/honeywell/software': typeof ProductsAccessControlHoneywellSoftwareRoute
  '/products/access-control/honeywell/upgrades': typeof ProductsAccessControlHoneywellUpgradesRoute
  '/products/access-control/salto/$productId': typeof ProductsAccessControlSaltoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/why-choose': typeof WhyChooseRoute
  '/products/access-control': typeof ProductsAccessControlRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
  '/about': typeof AboutIndexRoute
  '/sectors': typeof SectorsIndexRoute
  '/products/access-control/honeywell': typeof ProductsAccessControlHoneywellRoute
  '/products/access-control/salto': typeof ProductsAccessControlSaltoRoute
  '/products/access-control/honeywell/accessories': typeof ProductsAccessControlHoneywellAccessoriesRoute
  '/products/access-control/honeywell/control-panel-kits': typeof ProductsAccessControlHoneywellControlPanelKitsRoute
  '/products/access-control/honeywell/control-panels': typeof ProductsAccessControlHoneywellControlPanelsRoute
  '/products/access-control/honeywell/credentials': typeof ProductsAccessControlHoneywellCredentialsRoute
  '/products/access-control/honeywell/door-hardware': typeof ProductsAccessControlHoneywellDoorHardwareRoute
  '/products/access-control/honeywell/lobby-kiosks': typeof ProductsAccessControlHoneywellLobbyKiosksRoute
  '/products/access-control/honeywell/readers': typeof ProductsAccessControlHoneywellReadersRoute
  '/products/access-control/honeywell/software': typeof ProductsAccessControlHoneywellSoftwareRoute
  '/products/access-control/honeywell/upgrades': typeof ProductsAccessControlHoneywellUpgradesRoute
  '/products/access-control/salto/$productId': typeof ProductsAccessControlSaltoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/services': typeof ServicesRoute
  '/why-choose': typeof WhyChooseRoute
  '/products_/access-control': typeof ProductsAccessControlRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
  '/about/': typeof AboutIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/products_/access-control_/honeywell': typeof ProductsAccessControlHoneywellRoute
  '/products_/access-control_/salto': typeof ProductsAccessControlSaltoRoute
  '/products_/access-control_/honeywell_/accessories': typeof ProductsAccessControlHoneywellAccessoriesRoute
  '/products_/access-control_/honeywell_/control-panel-kits': typeof ProductsAccessControlHoneywellControlPanelKitsRoute
  '/products_/access-control_/honeywell_/control-panels': typeof ProductsAccessControlHoneywellControlPanelsRoute
  '/products_/access-control_/honeywell_/credentials': typeof ProductsAccessControlHoneywellCredentialsRoute
  '/products_/access-control_/honeywell_/door-hardware': typeof ProductsAccessControlHoneywellDoorHardwareRoute
  '/products_/access-control_/honeywell_/lobby-kiosks': typeof ProductsAccessControlHoneywellLobbyKiosksRoute
  '/products_/access-control_/honeywell_/readers': typeof ProductsAccessControlHoneywellReadersRoute
  '/products_/access-control_/honeywell_/software': typeof ProductsAccessControlHoneywellSoftwareRoute
  '/products_/access-control_/honeywell_/upgrades': typeof ProductsAccessControlHoneywellUpgradesRoute
  '/products_/access-control_/salto_/$productId': typeof ProductsAccessControlSaltoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/portfolio'
    | '/products'
    | '/projects'
    | '/sectors'
    | '/services'
    | '/why-choose'
    | '/products/access-control'
    | '/sectors/$sectorId'
    | '/about/'
    | '/sectors/'
    | '/products/access-control/honeywell'
    | '/products/access-control/salto'
    | '/products/access-control/honeywell/accessories'
    | '/products/access-control/honeywell/control-panel-kits'
    | '/products/access-control/honeywell/control-panels'
    | '/products/access-control/honeywell/credentials'
    | '/products/access-control/honeywell/door-hardware'
    | '/products/access-control/honeywell/lobby-kiosks'
    | '/products/access-control/honeywell/readers'
    | '/products/access-control/honeywell/software'
    | '/products/access-control/honeywell/upgrades'
    | '/products/access-control/salto/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/portfolio'
    | '/products'
    | '/projects'
    | '/services'
    | '/why-choose'
    | '/products/access-control'
    | '/sectors/$sectorId'
    | '/about'
    | '/sectors'
    | '/products/access-control/honeywell'
    | '/products/access-control/salto'
    | '/products/access-control/honeywell/accessories'
    | '/products/access-control/honeywell/control-panel-kits'
    | '/products/access-control/honeywell/control-panels'
    | '/products/access-control/honeywell/credentials'
    | '/products/access-control/honeywell/door-hardware'
    | '/products/access-control/honeywell/lobby-kiosks'
    | '/products/access-control/honeywell/readers'
    | '/products/access-control/honeywell/software'
    | '/products/access-control/honeywell/upgrades'
    | '/products/access-control/salto/$productId'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/portfolio'
    | '/products'
    | '/projects'
    | '/sectors'
    | '/services'
    | '/why-choose'
    | '/products_/access-control'
    | '/sectors/$sectorId'
    | '/about/'
    | '/sectors/'
    | '/products_/access-control_/honeywell'
    | '/products_/access-control_/salto'
    | '/products_/access-control_/honeywell_/accessories'
    | '/products_/access-control_/honeywell_/control-panel-kits'
    | '/products_/access-control_/honeywell_/control-panels'
    | '/products_/access-control_/honeywell_/credentials'
    | '/products_/access-control_/honeywell_/door-hardware'
    | '/products_/access-control_/honeywell_/lobby-kiosks'
    | '/products_/access-control_/honeywell_/readers'
    | '/products_/access-control_/honeywell_/software'
    | '/products_/access-control_/honeywell_/upgrades'
    | '/products_/access-control_/salto_/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  SectorsRoute: typeof SectorsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  WhyChooseRoute: typeof WhyChooseRoute
  ProductsAccessControlRoute: typeof ProductsAccessControlRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ProductsAccessControlHoneywellRoute: typeof ProductsAccessControlHoneywellRoute
  ProductsAccessControlSaltoRoute: typeof ProductsAccessControlSaltoRoute
  ProductsAccessControlHoneywellAccessoriesRoute: typeof ProductsAccessControlHoneywellAccessoriesRoute
  ProductsAccessControlHoneywellControlPanelKitsRoute: typeof ProductsAccessControlHoneywellControlPanelKitsRoute
  ProductsAccessControlHoneywellControlPanelsRoute: typeof ProductsAccessControlHoneywellControlPanelsRoute
  ProductsAccessControlHoneywellCredentialsRoute: typeof ProductsAccessControlHoneywellCredentialsRoute
  ProductsAccessControlHoneywellDoorHardwareRoute: typeof ProductsAccessControlHoneywellDoorHardwareRoute
  ProductsAccessControlHoneywellLobbyKiosksRoute: typeof ProductsAccessControlHoneywellLobbyKiosksRoute
  ProductsAccessControlHoneywellReadersRoute: typeof ProductsAccessControlHoneywellReadersRoute
  ProductsAccessControlHoneywellSoftwareRoute: typeof ProductsAccessControlHoneywellSoftwareRoute
  ProductsAccessControlHoneywellUpgradesRoute: typeof ProductsAccessControlHoneywellUpgradesRoute
  ProductsAccessControlSaltoProductIdRoute: typeof ProductsAccessControlSaltoProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose': {
      id: '/why-choose'
      path: '/why-choose'
      fullPath: '/why-choose'
      preLoaderRoute: typeof WhyChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/'
      fullPath: '/sectors/'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof SectorsRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$sectorId': {
      id: '/sectors/$sectorId'
      path: '/$sectorId'
      fullPath: '/sectors/$sectorId'
      preLoaderRoute: typeof SectorsSectorIdRouteImport
      parentRoute: typeof SectorsRoute
    }
    '/products_/access-control': {
      id: '/products_/access-control'
      path: '/products/access-control'
      fullPath: '/products/access-control'
      preLoaderRoute: typeof ProductsAccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/salto': {
      id: '/products_/access-control_/salto'
      path: '/products/access-control/salto'
      fullPath: '/products/access-control/salto'
      preLoaderRoute: typeof ProductsAccessControlSaltoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell': {
      id: '/products_/access-control_/honeywell'
      path: '/products/access-control/honeywell'
      fullPath: '/products/access-control/honeywell'
      preLoaderRoute: typeof ProductsAccessControlHoneywellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/salto_/$productId': {
      id: '/products_/access-control_/salto_/$productId'
      path: '/products/access-control/salto/$productId'
      fullPath: '/products/access-control/salto/$productId'
      preLoaderRoute: typeof ProductsAccessControlSaltoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/upgrades': {
      id: '/products_/access-control_/honeywell_/upgrades'
      path: '/products/access-control/honeywell/upgrades'
      fullPath: '/products/access-control/honeywell/upgrades'
      preLoaderRoute: typeof ProductsAccessControlHoneywellUpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/software': {
      id: '/products_/access-control_/honeywell_/software'
      path: '/products/access-control/honeywell/software'
      fullPath: '/products/access-control/honeywell/software'
      preLoaderRoute: typeof ProductsAccessControlHoneywellSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/readers': {
      id: '/products_/access-control_/honeywell_/readers'
      path: '/products/access-control/honeywell/readers'
      fullPath: '/products/access-control/honeywell/readers'
      preLoaderRoute: typeof ProductsAccessControlHoneywellReadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/lobby-kiosks': {
      id: '/products_/access-control_/honeywell_/lobby-kiosks'
      path: '/products/access-control/honeywell/lobby-kiosks'
      fullPath: '/products/access-control/honeywell/lobby-kiosks'
      preLoaderRoute: typeof ProductsAccessControlHoneywellLobbyKiosksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/door-hardware': {
      id: '/products_/access-control_/honeywell_/door-hardware'
      path: '/products/access-control/honeywell/door-hardware'
      fullPath: '/products/access-control/honeywell/door-hardware'
      preLoaderRoute: typeof ProductsAccessControlHoneywellDoorHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/credentials': {
      id: '/products_/access-control_/honeywell_/credentials'
      path: '/products/access-control/honeywell/credentials'
      fullPath: '/products/access-control/honeywell/credentials'
      preLoaderRoute: typeof ProductsAccessControlHoneywellCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/control-panels': {
      id: '/products_/access-control_/honeywell_/control-panels'
      path: '/products/access-control/honeywell/control-panels'
      fullPath: '/products/access-control/honeywell/control-panels'
      preLoaderRoute: typeof ProductsAccessControlHoneywellControlPanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/control-panel-kits': {
      id: '/products_/access-control_/honeywell_/control-panel-kits'
      path: '/products/access-control/honeywell/control-panel-kits'
      fullPath: '/products/access-control/honeywell/control-panel-kits'
      preLoaderRoute: typeof ProductsAccessControlHoneywellControlPanelKitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/access-control_/honeywell_/accessories': {
      id: '/products_/access-control_/honeywell_/accessories'
      path: '/products/access-control/honeywell/accessories'
      fullPath: '/products/access-control/honeywell/accessories'
      preLoaderRoute: typeof ProductsAccessControlHoneywellAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SectorsRouteChildren {
  SectorsSectorIdRoute: typeof SectorsSectorIdRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
}

const SectorsRouteChildren: SectorsRouteChildren = {
  SectorsSectorIdRoute: SectorsSectorIdRoute,
  SectorsIndexRoute: SectorsIndexRoute,
}

const SectorsRouteWithChildren =
  SectorsRoute._addFileChildren(SectorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  SectorsRoute: SectorsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  WhyChooseRoute: WhyChooseRoute,
  ProductsAccessControlRoute: ProductsAccessControlRoute,
  AboutIndexRoute: AboutIndexRoute,
  ProductsAccessControlHoneywellRoute: ProductsAccessControlHoneywellRoute,
  ProductsAccessControlSaltoRoute: ProductsAccessControlSaltoRoute,
  ProductsAccessControlHoneywellAccessoriesRoute:
    ProductsAccessControlHoneywellAccessoriesRoute,
  ProductsAccessControlHoneywellControlPanelKitsRoute:
    ProductsAccessControlHoneywellControlPanelKitsRoute,
  ProductsAccessControlHoneywellControlPanelsRoute:
    ProductsAccessControlHoneywellControlPanelsRoute,
  ProductsAccessControlHoneywellCredentialsRoute:
    ProductsAccessControlHoneywellCredentialsRoute,
  ProductsAccessControlHoneywellDoorHardwareRoute:
    ProductsAccessControlHoneywellDoorHardwareRoute,
  ProductsAccessControlHoneywellLobbyKiosksRoute:
    ProductsAccessControlHoneywellLobbyKiosksRoute,
  ProductsAccessControlHoneywellReadersRoute:
    ProductsAccessControlHoneywellReadersRoute,
  ProductsAccessControlHoneywellSoftwareRoute:
    ProductsAccessControlHoneywellSoftwareRoute,
  ProductsAccessControlHoneywellUpgradesRoute:
    ProductsAccessControlHoneywellUpgradesRoute,
  ProductsAccessControlSaltoProductIdRoute:
    ProductsAccessControlSaltoProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
