/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseRouteImport } from './routes/why-choose'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TechnicalTipsRouteImport } from './routes/technical-tips'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as DocumentCenterRouteImport } from './routes/document-center'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorsIndexRouteImport } from './routes/sectors.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ServicesVesdaRouteImport } from './routes/services_.vesda'
import { Route as ServicesSurveillanceRouteImport } from './routes/services_.surveillance'
import { Route as ServicesRoomControlRouteImport } from './routes/services_.room-control'
import { Route as ServicesPublicAddressRouteImport } from './routes/services_.public-address'
import { Route as ServicesLeakDetectionRouteImport } from './routes/services_.leak-detection'
import { Route as ServicesIntrusionSystemRouteImport } from './routes/services_.intrusion-system'
import { Route as ServicesFireAlarmRouteImport } from './routes/services_.fire-alarm'
import { Route as ServicesCustomSolutionRouteImport } from './routes/services_.custom-solution'
import { Route as ServicesCarParkingRouteImport } from './routes/services_.car-parking'
import { Route as ServicesBuildingManagementRouteImport } from './routes/services_.building-management'
import { Route as ServicesAudioVisualRouteImport } from './routes/services_.audio-visual'
import { Route as ServicesAccessControlRouteImport } from './routes/services_.access-control'
import { Route as SectorsSectorIdRouteImport } from './routes/sectors.$sectorId'
import { Route as InsightsRetrofittingHeritageRouteImport } from './routes/insights.retrofitting-heritage'
import { Route as InsightsRaffleBookstoreRouteImport } from './routes/insights.raffle-bookstore'
import { Route as InsightsKrohomBookstoreRouteImport } from './routes/insights.krohom-bookstore'
import { Route as InsightsKohPichCommercialComplexRouteImport } from './routes/insights.koh-pich-commercial-complex'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ProductsSurveillanceIndexRouteImport } from './routes/products.surveillance.index'
import { Route as ProductsBuildingManagementIndexRouteImport } from './routes/products.building-management.index'
import { Route as ProductsAccessControlIndexRouteImport } from './routes/products.access-control.index'
import { Route as ProductsDetailProductIdRouteImport } from './routes/products.detail.$productId'
import { Route as ProductsAccessControlSaltoIndexRouteImport } from './routes/products.access-control.salto.index'
import { Route as ProductsAccessControlHoneywellIndexRouteImport } from './routes/products.access-control.honeywell.index'
import { Route as ProductsAccessControlSaltoProductIdRouteImport } from './routes/products.access-control.salto.$productId'
import { Route as ProductsAccessControlHoneywellUpgradesRouteImport } from './routes/products.access-control.honeywell.upgrades'
import { Route as ProductsAccessControlHoneywellSoftwareRouteImport } from './routes/products.access-control.honeywell.software'
import { Route as ProductsAccessControlHoneywellReadersRouteImport } from './routes/products.access-control.honeywell.readers'
import { Route as ProductsAccessControlHoneywellLobbyKiosksRouteImport } from './routes/products.access-control.honeywell.lobby-kiosks'
import { Route as ProductsAccessControlHoneywellDoorHardwareRouteImport } from './routes/products.access-control.honeywell.door-hardware'
import { Route as ProductsAccessControlHoneywellCredentialsRouteImport } from './routes/products.access-control.honeywell.credentials'
import { Route as ProductsAccessControlHoneywellControlPanelsRouteImport } from './routes/products.access-control.honeywell.control-panels'
import { Route as ProductsAccessControlHoneywellControlPanelKitsRouteImport } from './routes/products.access-control.honeywell.control-panel-kits'
import { Route as ProductsAccessControlHoneywellAccessoriesRouteImport } from './routes/products.access-control.honeywell.accessories'

const WhyChooseRoute = WhyChooseRouteImport.update({
  id: '/why-choose',
  path: '/why-choose',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalTipsRoute = TechnicalTipsRouteImport.update({
  id: '/technical-tips',
  path: '/technical-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentCenterRoute = DocumentCenterRouteImport.update({
  id: '/document-center',
  path: '/document-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SectorsRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVesdaRoute = ServicesVesdaRouteImport.update({
  id: '/services_/vesda',
  path: '/services/vesda',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSurveillanceRoute = ServicesSurveillanceRouteImport.update({
  id: '/services_/surveillance',
  path: '/services/surveillance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoomControlRoute = ServicesRoomControlRouteImport.update({
  id: '/services_/room-control',
  path: '/services/room-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPublicAddressRoute = ServicesPublicAddressRouteImport.update({
  id: '/services_/public-address',
  path: '/services/public-address',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeakDetectionRoute = ServicesLeakDetectionRouteImport.update({
  id: '/services_/leak-detection',
  path: '/services/leak-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIntrusionSystemRoute = ServicesIntrusionSystemRouteImport.update({
  id: '/services_/intrusion-system',
  path: '/services/intrusion-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFireAlarmRoute = ServicesFireAlarmRouteImport.update({
  id: '/services_/fire-alarm',
  path: '/services/fire-alarm',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomSolutionRoute = ServicesCustomSolutionRouteImport.update({
  id: '/services_/custom-solution',
  path: '/services/custom-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCarParkingRoute = ServicesCarParkingRouteImport.update({
  id: '/services_/car-parking',
  path: '/services/car-parking',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBuildingManagementRoute =
  ServicesBuildingManagementRouteImport.update({
    id: '/services_/building-management',
    path: '/services/building-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAudioVisualRoute = ServicesAudioVisualRouteImport.update({
  id: '/services_/audio-visual',
  path: '/services/audio-visual',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAccessControlRoute = ServicesAccessControlRouteImport.update({
  id: '/services_/access-control',
  path: '/services/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSectorIdRoute = SectorsSectorIdRouteImport.update({
  id: '/$sectorId',
  path: '/$sectorId',
  getParentRoute: () => SectorsRoute,
} as any)
const InsightsRetrofittingHeritageRoute =
  InsightsRetrofittingHeritageRouteImport.update({
    id: '/insights/retrofitting-heritage',
    path: '/insights/retrofitting-heritage',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsRaffleBookstoreRoute = InsightsRaffleBookstoreRouteImport.update({
  id: '/insights/raffle-bookstore',
  path: '/insights/raffle-bookstore',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsKrohomBookstoreRoute = InsightsKrohomBookstoreRouteImport.update({
  id: '/insights/krohom-bookstore',
  path: '/insights/krohom-bookstore',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsKohPichCommercialComplexRoute =
  InsightsKohPichCommercialComplexRouteImport.update({
    id: '/insights/koh-pich-commercial-complex',
    path: '/insights/koh-pich-commercial-complex',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSurveillanceIndexRoute =
  ProductsSurveillanceIndexRouteImport.update({
    id: '/surveillance/',
    path: '/surveillance/',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsBuildingManagementIndexRoute =
  ProductsBuildingManagementIndexRouteImport.update({
    id: '/building-management/',
    path: '/building-management/',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlIndexRoute =
  ProductsAccessControlIndexRouteImport.update({
    id: '/access-control/',
    path: '/access-control/',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsDetailProductIdRoute = ProductsDetailProductIdRouteImport.update({
  id: '/detail/$productId',
  path: '/detail/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsAccessControlSaltoIndexRoute =
  ProductsAccessControlSaltoIndexRouteImport.update({
    id: '/access-control/salto/',
    path: '/access-control/salto/',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellIndexRoute =
  ProductsAccessControlHoneywellIndexRouteImport.update({
    id: '/access-control/honeywell/',
    path: '/access-control/honeywell/',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlSaltoProductIdRoute =
  ProductsAccessControlSaltoProductIdRouteImport.update({
    id: '/access-control/salto/$productId',
    path: '/access-control/salto/$productId',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellUpgradesRoute =
  ProductsAccessControlHoneywellUpgradesRouteImport.update({
    id: '/access-control/honeywell/upgrades',
    path: '/access-control/honeywell/upgrades',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellSoftwareRoute =
  ProductsAccessControlHoneywellSoftwareRouteImport.update({
    id: '/access-control/honeywell/software',
    path: '/access-control/honeywell/software',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellReadersRoute =
  ProductsAccessControlHoneywellReadersRouteImport.update({
    id: '/access-control/honeywell/readers',
    path: '/access-control/honeywell/readers',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellLobbyKiosksRoute =
  ProductsAccessControlHoneywellLobbyKiosksRouteImport.update({
    id: '/access-control/honeywell/lobby-kiosks',
    path: '/access-control/honeywell/lobby-kiosks',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellDoorHardwareRoute =
  ProductsAccessControlHoneywellDoorHardwareRouteImport.update({
    id: '/access-control/honeywell/door-hardware',
    path: '/access-control/honeywell/door-hardware',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellCredentialsRoute =
  ProductsAccessControlHoneywellCredentialsRouteImport.update({
    id: '/access-control/honeywell/credentials',
    path: '/access-control/honeywell/credentials',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellControlPanelsRoute =
  ProductsAccessControlHoneywellControlPanelsRouteImport.update({
    id: '/access-control/honeywell/control-panels',
    path: '/access-control/honeywell/control-panels',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellControlPanelKitsRoute =
  ProductsAccessControlHoneywellControlPanelKitsRouteImport.update({
    id: '/access-control/honeywell/control-panel-kits',
    path: '/access-control/honeywell/control-panel-kits',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsAccessControlHoneywellAccessoriesRoute =
  ProductsAccessControlHoneywellAccessoriesRouteImport.update({
    id: '/access-control/honeywell/accessories',
    path: '/access-control/honeywell/accessories',
    getParentRoute: () => ProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/document-center': typeof DocumentCenterRoute
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/technical-tips': typeof TechnicalTipsRoute
  '/warranty': typeof WarrantyRoute
  '/why-choose': typeof WhyChooseRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/koh-pich-commercial-complex': typeof InsightsKohPichCommercialComplexRoute
  '/insights/krohom-bookstore': typeof InsightsKrohomBookstoreRoute
  '/insights/raffle-bookstore': typeof InsightsRaffleBookstoreRoute
  '/insights/retrofitting-heritage': typeof InsightsRetrofittingHeritageRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
  '/services/access-control': typeof ServicesAccessControlRoute
  '/services/audio-visual': typeof ServicesAudioVisualRoute
  '/services/building-management': typeof ServicesBuildingManagementRoute
  '/services/car-parking': typeof ServicesCarParkingRoute
  '/services/custom-solution': typeof ServicesCustomSolutionRoute
  '/services/fire-alarm': typeof ServicesFireAlarmRoute
  '/services/intrusion-system': typeof ServicesIntrusionSystemRoute
  '/services/leak-detection': typeof ServicesLeakDetectionRoute
  '/services/public-address': typeof ServicesPublicAddressRoute
  '/services/room-control': typeof ServicesRoomControlRoute
  '/services/surveillance': typeof ServicesSurveillanceRoute
  '/services/vesda': typeof ServicesVesdaRoute
  '/about/': typeof AboutIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/products/detail/$productId': typeof ProductsDetailProductIdRoute
  '/products/access-control/': typeof ProductsAccessControlIndexRoute
  '/products/building-management/': typeof ProductsBuildingManagementIndexRoute
  '/products/surveillance/': typeof ProductsSurveillanceIndexRoute
  '/products/access-control/honeywell/accessories': typeof ProductsAccessControlHoneywellAccessoriesRoute
  '/products/access-control/honeywell/control-panel-kits': typeof ProductsAccessControlHoneywellControlPanelKitsRoute
  '/products/access-control/honeywell/control-panels': typeof ProductsAccessControlHoneywellControlPanelsRoute
  '/products/access-control/honeywell/credentials': typeof ProductsAccessControlHoneywellCredentialsRoute
  '/products/access-control/honeywell/door-hardware': typeof ProductsAccessControlHoneywellDoorHardwareRoute
  '/products/access-control/honeywell/lobby-kiosks': typeof ProductsAccessControlHoneywellLobbyKiosksRoute
  '/products/access-control/honeywell/readers': typeof ProductsAccessControlHoneywellReadersRoute
  '/products/access-control/honeywell/software': typeof ProductsAccessControlHoneywellSoftwareRoute
  '/products/access-control/honeywell/upgrades': typeof ProductsAccessControlHoneywellUpgradesRoute
  '/products/access-control/salto/$productId': typeof ProductsAccessControlSaltoProductIdRoute
  '/products/access-control/honeywell/': typeof ProductsAccessControlHoneywellIndexRoute
  '/products/access-control/salto/': typeof ProductsAccessControlSaltoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/document-center': typeof DocumentCenterRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/technical-tips': typeof TechnicalTipsRoute
  '/warranty': typeof WarrantyRoute
  '/why-choose': typeof WhyChooseRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/koh-pich-commercial-complex': typeof InsightsKohPichCommercialComplexRoute
  '/insights/krohom-bookstore': typeof InsightsKrohomBookstoreRoute
  '/insights/raffle-bookstore': typeof InsightsRaffleBookstoreRoute
  '/insights/retrofitting-heritage': typeof InsightsRetrofittingHeritageRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
  '/services/access-control': typeof ServicesAccessControlRoute
  '/services/audio-visual': typeof ServicesAudioVisualRoute
  '/services/building-management': typeof ServicesBuildingManagementRoute
  '/services/car-parking': typeof ServicesCarParkingRoute
  '/services/custom-solution': typeof ServicesCustomSolutionRoute
  '/services/fire-alarm': typeof ServicesFireAlarmRoute
  '/services/intrusion-system': typeof ServicesIntrusionSystemRoute
  '/services/leak-detection': typeof ServicesLeakDetectionRoute
  '/services/public-address': typeof ServicesPublicAddressRoute
  '/services/room-control': typeof ServicesRoomControlRoute
  '/services/surveillance': typeof ServicesSurveillanceRoute
  '/services/vesda': typeof ServicesVesdaRoute
  '/about': typeof AboutIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/sectors': typeof SectorsIndexRoute
  '/products/detail/$productId': typeof ProductsDetailProductIdRoute
  '/products/access-control': typeof ProductsAccessControlIndexRoute
  '/products/building-management': typeof ProductsBuildingManagementIndexRoute
  '/products/surveillance': typeof ProductsSurveillanceIndexRoute
  '/products/access-control/honeywell/accessories': typeof ProductsAccessControlHoneywellAccessoriesRoute
  '/products/access-control/honeywell/control-panel-kits': typeof ProductsAccessControlHoneywellControlPanelKitsRoute
  '/products/access-control/honeywell/control-panels': typeof ProductsAccessControlHoneywellControlPanelsRoute
  '/products/access-control/honeywell/credentials': typeof ProductsAccessControlHoneywellCredentialsRoute
  '/products/access-control/honeywell/door-hardware': typeof ProductsAccessControlHoneywellDoorHardwareRoute
  '/products/access-control/honeywell/lobby-kiosks': typeof ProductsAccessControlHoneywellLobbyKiosksRoute
  '/products/access-control/honeywell/readers': typeof ProductsAccessControlHoneywellReadersRoute
  '/products/access-control/honeywell/software': typeof ProductsAccessControlHoneywellSoftwareRoute
  '/products/access-control/honeywell/upgrades': typeof ProductsAccessControlHoneywellUpgradesRoute
  '/products/access-control/salto/$productId': typeof ProductsAccessControlSaltoProductIdRoute
  '/products/access-control/honeywell': typeof ProductsAccessControlHoneywellIndexRoute
  '/products/access-control/salto': typeof ProductsAccessControlSaltoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/document-center': typeof DocumentCenterRoute
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/sectors': typeof SectorsRouteWithChildren
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/technical-tips': typeof TechnicalTipsRoute
  '/warranty': typeof WarrantyRoute
  '/why-choose': typeof WhyChooseRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/koh-pich-commercial-complex': typeof InsightsKohPichCommercialComplexRoute
  '/insights/krohom-bookstore': typeof InsightsKrohomBookstoreRoute
  '/insights/raffle-bookstore': typeof InsightsRaffleBookstoreRoute
  '/insights/retrofitting-heritage': typeof InsightsRetrofittingHeritageRoute
  '/sectors/$sectorId': typeof SectorsSectorIdRoute
  '/services_/access-control': typeof ServicesAccessControlRoute
  '/services_/audio-visual': typeof ServicesAudioVisualRoute
  '/services_/building-management': typeof ServicesBuildingManagementRoute
  '/services_/car-parking': typeof ServicesCarParkingRoute
  '/services_/custom-solution': typeof ServicesCustomSolutionRoute
  '/services_/fire-alarm': typeof ServicesFireAlarmRoute
  '/services_/intrusion-system': typeof ServicesIntrusionSystemRoute
  '/services_/leak-detection': typeof ServicesLeakDetectionRoute
  '/services_/public-address': typeof ServicesPublicAddressRoute
  '/services_/room-control': typeof ServicesRoomControlRoute
  '/services_/surveillance': typeof ServicesSurveillanceRoute
  '/services_/vesda': typeof ServicesVesdaRoute
  '/about/': typeof AboutIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/products/detail/$productId': typeof ProductsDetailProductIdRoute
  '/products/access-control/': typeof ProductsAccessControlIndexRoute
  '/products/building-management/': typeof ProductsBuildingManagementIndexRoute
  '/products/surveillance/': typeof ProductsSurveillanceIndexRoute
  '/products/access-control/honeywell/accessories': typeof ProductsAccessControlHoneywellAccessoriesRoute
  '/products/access-control/honeywell/control-panel-kits': typeof ProductsAccessControlHoneywellControlPanelKitsRoute
  '/products/access-control/honeywell/control-panels': typeof ProductsAccessControlHoneywellControlPanelsRoute
  '/products/access-control/honeywell/credentials': typeof ProductsAccessControlHoneywellCredentialsRoute
  '/products/access-control/honeywell/door-hardware': typeof ProductsAccessControlHoneywellDoorHardwareRoute
  '/products/access-control/honeywell/lobby-kiosks': typeof ProductsAccessControlHoneywellLobbyKiosksRoute
  '/products/access-control/honeywell/readers': typeof ProductsAccessControlHoneywellReadersRoute
  '/products/access-control/honeywell/software': typeof ProductsAccessControlHoneywellSoftwareRoute
  '/products/access-control/honeywell/upgrades': typeof ProductsAccessControlHoneywellUpgradesRoute
  '/products/access-control/salto/$productId': typeof ProductsAccessControlSaltoProductIdRoute
  '/products/access-control/honeywell/': typeof ProductsAccessControlHoneywellIndexRoute
  '/products/access-control/salto/': typeof ProductsAccessControlSaltoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/credentials'
    | '/document-center'
    | '/portfolio'
    | '/products'
    | '/projects'
    | '/request-quote'
    | '/sectors'
    | '/services'
    | '/support'
    | '/technical-tips'
    | '/warranty'
    | '/why-choose'
    | '/insights/$slug'
    | '/insights/koh-pich-commercial-complex'
    | '/insights/krohom-bookstore'
    | '/insights/raffle-bookstore'
    | '/insights/retrofitting-heritage'
    | '/sectors/$sectorId'
    | '/services/access-control'
    | '/services/audio-visual'
    | '/services/building-management'
    | '/services/car-parking'
    | '/services/custom-solution'
    | '/services/fire-alarm'
    | '/services/intrusion-system'
    | '/services/leak-detection'
    | '/services/public-address'
    | '/services/room-control'
    | '/services/surveillance'
    | '/services/vesda'
    | '/about/'
    | '/insights/'
    | '/products/'
    | '/sectors/'
    | '/products/detail/$productId'
    | '/products/access-control/'
    | '/products/building-management/'
    | '/products/surveillance/'
    | '/products/access-control/honeywell/accessories'
    | '/products/access-control/honeywell/control-panel-kits'
    | '/products/access-control/honeywell/control-panels'
    | '/products/access-control/honeywell/credentials'
    | '/products/access-control/honeywell/door-hardware'
    | '/products/access-control/honeywell/lobby-kiosks'
    | '/products/access-control/honeywell/readers'
    | '/products/access-control/honeywell/software'
    | '/products/access-control/honeywell/upgrades'
    | '/products/access-control/salto/$productId'
    | '/products/access-control/honeywell/'
    | '/products/access-control/salto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/credentials'
    | '/document-center'
    | '/portfolio'
    | '/projects'
    | '/request-quote'
    | '/services'
    | '/support'
    | '/technical-tips'
    | '/warranty'
    | '/why-choose'
    | '/insights/$slug'
    | '/insights/koh-pich-commercial-complex'
    | '/insights/krohom-bookstore'
    | '/insights/raffle-bookstore'
    | '/insights/retrofitting-heritage'
    | '/sectors/$sectorId'
    | '/services/access-control'
    | '/services/audio-visual'
    | '/services/building-management'
    | '/services/car-parking'
    | '/services/custom-solution'
    | '/services/fire-alarm'
    | '/services/intrusion-system'
    | '/services/leak-detection'
    | '/services/public-address'
    | '/services/room-control'
    | '/services/surveillance'
    | '/services/vesda'
    | '/about'
    | '/insights'
    | '/products'
    | '/sectors'
    | '/products/detail/$productId'
    | '/products/access-control'
    | '/products/building-management'
    | '/products/surveillance'
    | '/products/access-control/honeywell/accessories'
    | '/products/access-control/honeywell/control-panel-kits'
    | '/products/access-control/honeywell/control-panels'
    | '/products/access-control/honeywell/credentials'
    | '/products/access-control/honeywell/door-hardware'
    | '/products/access-control/honeywell/lobby-kiosks'
    | '/products/access-control/honeywell/readers'
    | '/products/access-control/honeywell/software'
    | '/products/access-control/honeywell/upgrades'
    | '/products/access-control/salto/$productId'
    | '/products/access-control/honeywell'
    | '/products/access-control/salto'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/credentials'
    | '/document-center'
    | '/portfolio'
    | '/products'
    | '/projects'
    | '/request-quote'
    | '/sectors'
    | '/services'
    | '/support'
    | '/technical-tips'
    | '/warranty'
    | '/why-choose'
    | '/insights/$slug'
    | '/insights/koh-pich-commercial-complex'
    | '/insights/krohom-bookstore'
    | '/insights/raffle-bookstore'
    | '/insights/retrofitting-heritage'
    | '/sectors/$sectorId'
    | '/services_/access-control'
    | '/services_/audio-visual'
    | '/services_/building-management'
    | '/services_/car-parking'
    | '/services_/custom-solution'
    | '/services_/fire-alarm'
    | '/services_/intrusion-system'
    | '/services_/leak-detection'
    | '/services_/public-address'
    | '/services_/room-control'
    | '/services_/surveillance'
    | '/services_/vesda'
    | '/about/'
    | '/insights/'
    | '/products/'
    | '/sectors/'
    | '/products/detail/$productId'
    | '/products/access-control/'
    | '/products/building-management/'
    | '/products/surveillance/'
    | '/products/access-control/honeywell/accessories'
    | '/products/access-control/honeywell/control-panel-kits'
    | '/products/access-control/honeywell/control-panels'
    | '/products/access-control/honeywell/credentials'
    | '/products/access-control/honeywell/door-hardware'
    | '/products/access-control/honeywell/lobby-kiosks'
    | '/products/access-control/honeywell/readers'
    | '/products/access-control/honeywell/software'
    | '/products/access-control/honeywell/upgrades'
    | '/products/access-control/salto/$productId'
    | '/products/access-control/honeywell/'
    | '/products/access-control/salto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CredentialsRoute: typeof CredentialsRoute
  DocumentCenterRoute: typeof DocumentCenterRoute
  PortfolioRoute: typeof PortfolioRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  SectorsRoute: typeof SectorsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SupportRoute: typeof SupportRoute
  TechnicalTipsRoute: typeof TechnicalTipsRoute
  WarrantyRoute: typeof WarrantyRoute
  WhyChooseRoute: typeof WhyChooseRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsKohPichCommercialComplexRoute: typeof InsightsKohPichCommercialComplexRoute
  InsightsKrohomBookstoreRoute: typeof InsightsKrohomBookstoreRoute
  InsightsRaffleBookstoreRoute: typeof InsightsRaffleBookstoreRoute
  InsightsRetrofittingHeritageRoute: typeof InsightsRetrofittingHeritageRoute
  ServicesAccessControlRoute: typeof ServicesAccessControlRoute
  ServicesAudioVisualRoute: typeof ServicesAudioVisualRoute
  ServicesBuildingManagementRoute: typeof ServicesBuildingManagementRoute
  ServicesCarParkingRoute: typeof ServicesCarParkingRoute
  ServicesCustomSolutionRoute: typeof ServicesCustomSolutionRoute
  ServicesFireAlarmRoute: typeof ServicesFireAlarmRoute
  ServicesIntrusionSystemRoute: typeof ServicesIntrusionSystemRoute
  ServicesLeakDetectionRoute: typeof ServicesLeakDetectionRoute
  ServicesPublicAddressRoute: typeof ServicesPublicAddressRoute
  ServicesRoomControlRoute: typeof ServicesRoomControlRoute
  ServicesSurveillanceRoute: typeof ServicesSurveillanceRoute
  ServicesVesdaRoute: typeof ServicesVesdaRoute
  AboutIndexRoute: typeof AboutIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose': {
      id: '/why-choose'
      path: '/why-choose'
      fullPath: '/why-choose'
      preLoaderRoute: typeof WhyChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-tips': {
      id: '/technical-tips'
      path: '/technical-tips'
      fullPath: '/technical-tips'
      preLoaderRoute: typeof TechnicalTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-center': {
      id: '/document-center'
      path: '/document-center'
      fullPath: '/document-center'
      preLoaderRoute: typeof DocumentCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/'
      fullPath: '/sectors/'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof SectorsRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/vesda': {
      id: '/services_/vesda'
      path: '/services/vesda'
      fullPath: '/services/vesda'
      preLoaderRoute: typeof ServicesVesdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/surveillance': {
      id: '/services_/surveillance'
      path: '/services/surveillance'
      fullPath: '/services/surveillance'
      preLoaderRoute: typeof ServicesSurveillanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/room-control': {
      id: '/services_/room-control'
      path: '/services/room-control'
      fullPath: '/services/room-control'
      preLoaderRoute: typeof ServicesRoomControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/public-address': {
      id: '/services_/public-address'
      path: '/services/public-address'
      fullPath: '/services/public-address'
      preLoaderRoute: typeof ServicesPublicAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/leak-detection': {
      id: '/services_/leak-detection'
      path: '/services/leak-detection'
      fullPath: '/services/leak-detection'
      preLoaderRoute: typeof ServicesLeakDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/intrusion-system': {
      id: '/services_/intrusion-system'
      path: '/services/intrusion-system'
      fullPath: '/services/intrusion-system'
      preLoaderRoute: typeof ServicesIntrusionSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/fire-alarm': {
      id: '/services_/fire-alarm'
      path: '/services/fire-alarm'
      fullPath: '/services/fire-alarm'
      preLoaderRoute: typeof ServicesFireAlarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/custom-solution': {
      id: '/services_/custom-solution'
      path: '/services/custom-solution'
      fullPath: '/services/custom-solution'
      preLoaderRoute: typeof ServicesCustomSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/car-parking': {
      id: '/services_/car-parking'
      path: '/services/car-parking'
      fullPath: '/services/car-parking'
      preLoaderRoute: typeof ServicesCarParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/building-management': {
      id: '/services_/building-management'
      path: '/services/building-management'
      fullPath: '/services/building-management'
      preLoaderRoute: typeof ServicesBuildingManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/audio-visual': {
      id: '/services_/audio-visual'
      path: '/services/audio-visual'
      fullPath: '/services/audio-visual'
      preLoaderRoute: typeof ServicesAudioVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/access-control': {
      id: '/services_/access-control'
      path: '/services/access-control'
      fullPath: '/services/access-control'
      preLoaderRoute: typeof ServicesAccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$sectorId': {
      id: '/sectors/$sectorId'
      path: '/$sectorId'
      fullPath: '/sectors/$sectorId'
      preLoaderRoute: typeof SectorsSectorIdRouteImport
      parentRoute: typeof SectorsRoute
    }
    '/insights/retrofitting-heritage': {
      id: '/insights/retrofitting-heritage'
      path: '/insights/retrofitting-heritage'
      fullPath: '/insights/retrofitting-heritage'
      preLoaderRoute: typeof InsightsRetrofittingHeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/raffle-bookstore': {
      id: '/insights/raffle-bookstore'
      path: '/insights/raffle-bookstore'
      fullPath: '/insights/raffle-bookstore'
      preLoaderRoute: typeof InsightsRaffleBookstoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/krohom-bookstore': {
      id: '/insights/krohom-bookstore'
      path: '/insights/krohom-bookstore'
      fullPath: '/insights/krohom-bookstore'
      preLoaderRoute: typeof InsightsKrohomBookstoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/koh-pich-commercial-complex': {
      id: '/insights/koh-pich-commercial-complex'
      path: '/insights/koh-pich-commercial-complex'
      fullPath: '/insights/koh-pich-commercial-complex'
      preLoaderRoute: typeof InsightsKohPichCommercialComplexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/surveillance/': {
      id: '/products/surveillance/'
      path: '/surveillance'
      fullPath: '/products/surveillance/'
      preLoaderRoute: typeof ProductsSurveillanceIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/building-management/': {
      id: '/products/building-management/'
      path: '/building-management'
      fullPath: '/products/building-management/'
      preLoaderRoute: typeof ProductsBuildingManagementIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/': {
      id: '/products/access-control/'
      path: '/access-control'
      fullPath: '/products/access-control/'
      preLoaderRoute: typeof ProductsAccessControlIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/detail/$productId': {
      id: '/products/detail/$productId'
      path: '/detail/$productId'
      fullPath: '/products/detail/$productId'
      preLoaderRoute: typeof ProductsDetailProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/salto/': {
      id: '/products/access-control/salto/'
      path: '/access-control/salto'
      fullPath: '/products/access-control/salto/'
      preLoaderRoute: typeof ProductsAccessControlSaltoIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/': {
      id: '/products/access-control/honeywell/'
      path: '/access-control/honeywell'
      fullPath: '/products/access-control/honeywell/'
      preLoaderRoute: typeof ProductsAccessControlHoneywellIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/salto/$productId': {
      id: '/products/access-control/salto/$productId'
      path: '/access-control/salto/$productId'
      fullPath: '/products/access-control/salto/$productId'
      preLoaderRoute: typeof ProductsAccessControlSaltoProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/upgrades': {
      id: '/products/access-control/honeywell/upgrades'
      path: '/access-control/honeywell/upgrades'
      fullPath: '/products/access-control/honeywell/upgrades'
      preLoaderRoute: typeof ProductsAccessControlHoneywellUpgradesRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/software': {
      id: '/products/access-control/honeywell/software'
      path: '/access-control/honeywell/software'
      fullPath: '/products/access-control/honeywell/software'
      preLoaderRoute: typeof ProductsAccessControlHoneywellSoftwareRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/readers': {
      id: '/products/access-control/honeywell/readers'
      path: '/access-control/honeywell/readers'
      fullPath: '/products/access-control/honeywell/readers'
      preLoaderRoute: typeof ProductsAccessControlHoneywellReadersRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/lobby-kiosks': {
      id: '/products/access-control/honeywell/lobby-kiosks'
      path: '/access-control/honeywell/lobby-kiosks'
      fullPath: '/products/access-control/honeywell/lobby-kiosks'
      preLoaderRoute: typeof ProductsAccessControlHoneywellLobbyKiosksRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/door-hardware': {
      id: '/products/access-control/honeywell/door-hardware'
      path: '/access-control/honeywell/door-hardware'
      fullPath: '/products/access-control/honeywell/door-hardware'
      preLoaderRoute: typeof ProductsAccessControlHoneywellDoorHardwareRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/credentials': {
      id: '/products/access-control/honeywell/credentials'
      path: '/access-control/honeywell/credentials'
      fullPath: '/products/access-control/honeywell/credentials'
      preLoaderRoute: typeof ProductsAccessControlHoneywellCredentialsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/control-panels': {
      id: '/products/access-control/honeywell/control-panels'
      path: '/access-control/honeywell/control-panels'
      fullPath: '/products/access-control/honeywell/control-panels'
      preLoaderRoute: typeof ProductsAccessControlHoneywellControlPanelsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/control-panel-kits': {
      id: '/products/access-control/honeywell/control-panel-kits'
      path: '/access-control/honeywell/control-panel-kits'
      fullPath: '/products/access-control/honeywell/control-panel-kits'
      preLoaderRoute: typeof ProductsAccessControlHoneywellControlPanelKitsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/access-control/honeywell/accessories': {
      id: '/products/access-control/honeywell/accessories'
      path: '/access-control/honeywell/accessories'
      fullPath: '/products/access-control/honeywell/accessories'
      preLoaderRoute: typeof ProductsAccessControlHoneywellAccessoriesRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsDetailProductIdRoute: typeof ProductsDetailProductIdRoute
  ProductsAccessControlIndexRoute: typeof ProductsAccessControlIndexRoute
  ProductsBuildingManagementIndexRoute: typeof ProductsBuildingManagementIndexRoute
  ProductsSurveillanceIndexRoute: typeof ProductsSurveillanceIndexRoute
  ProductsAccessControlHoneywellAccessoriesRoute: typeof ProductsAccessControlHoneywellAccessoriesRoute
  ProductsAccessControlHoneywellControlPanelKitsRoute: typeof ProductsAccessControlHoneywellControlPanelKitsRoute
  ProductsAccessControlHoneywellControlPanelsRoute: typeof ProductsAccessControlHoneywellControlPanelsRoute
  ProductsAccessControlHoneywellCredentialsRoute: typeof ProductsAccessControlHoneywellCredentialsRoute
  ProductsAccessControlHoneywellDoorHardwareRoute: typeof ProductsAccessControlHoneywellDoorHardwareRoute
  ProductsAccessControlHoneywellLobbyKiosksRoute: typeof ProductsAccessControlHoneywellLobbyKiosksRoute
  ProductsAccessControlHoneywellReadersRoute: typeof ProductsAccessControlHoneywellReadersRoute
  ProductsAccessControlHoneywellSoftwareRoute: typeof ProductsAccessControlHoneywellSoftwareRoute
  ProductsAccessControlHoneywellUpgradesRoute: typeof ProductsAccessControlHoneywellUpgradesRoute
  ProductsAccessControlSaltoProductIdRoute: typeof ProductsAccessControlSaltoProductIdRoute
  ProductsAccessControlHoneywellIndexRoute: typeof ProductsAccessControlHoneywellIndexRoute
  ProductsAccessControlSaltoIndexRoute: typeof ProductsAccessControlSaltoIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsDetailProductIdRoute: ProductsDetailProductIdRoute,
  ProductsAccessControlIndexRoute: ProductsAccessControlIndexRoute,
  ProductsBuildingManagementIndexRoute: ProductsBuildingManagementIndexRoute,
  ProductsSurveillanceIndexRoute: ProductsSurveillanceIndexRoute,
  ProductsAccessControlHoneywellAccessoriesRoute:
    ProductsAccessControlHoneywellAccessoriesRoute,
  ProductsAccessControlHoneywellControlPanelKitsRoute:
    ProductsAccessControlHoneywellControlPanelKitsRoute,
  ProductsAccessControlHoneywellControlPanelsRoute:
    ProductsAccessControlHoneywellControlPanelsRoute,
  ProductsAccessControlHoneywellCredentialsRoute:
    ProductsAccessControlHoneywellCredentialsRoute,
  ProductsAccessControlHoneywellDoorHardwareRoute:
    ProductsAccessControlHoneywellDoorHardwareRoute,
  ProductsAccessControlHoneywellLobbyKiosksRoute:
    ProductsAccessControlHoneywellLobbyKiosksRoute,
  ProductsAccessControlHoneywellReadersRoute:
    ProductsAccessControlHoneywellReadersRoute,
  ProductsAccessControlHoneywellSoftwareRoute:
    ProductsAccessControlHoneywellSoftwareRoute,
  ProductsAccessControlHoneywellUpgradesRoute:
    ProductsAccessControlHoneywellUpgradesRoute,
  ProductsAccessControlSaltoProductIdRoute:
    ProductsAccessControlSaltoProductIdRoute,
  ProductsAccessControlHoneywellIndexRoute:
    ProductsAccessControlHoneywellIndexRoute,
  ProductsAccessControlSaltoIndexRoute: ProductsAccessControlSaltoIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface SectorsRouteChildren {
  SectorsSectorIdRoute: typeof SectorsSectorIdRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
}

const SectorsRouteChildren: SectorsRouteChildren = {
  SectorsSectorIdRoute: SectorsSectorIdRoute,
  SectorsIndexRoute: SectorsIndexRoute,
}

const SectorsRouteWithChildren =
  SectorsRoute._addFileChildren(SectorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CredentialsRoute: CredentialsRoute,
  DocumentCenterRoute: DocumentCenterRoute,
  PortfolioRoute: PortfolioRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  SectorsRoute: SectorsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SupportRoute: SupportRoute,
  TechnicalTipsRoute: TechnicalTipsRoute,
  WarrantyRoute: WarrantyRoute,
  WhyChooseRoute: WhyChooseRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsKohPichCommercialComplexRoute: InsightsKohPichCommercialComplexRoute,
  InsightsKrohomBookstoreRoute: InsightsKrohomBookstoreRoute,
  InsightsRaffleBookstoreRoute: InsightsRaffleBookstoreRoute,
  InsightsRetrofittingHeritageRoute: InsightsRetrofittingHeritageRoute,
  ServicesAccessControlRoute: ServicesAccessControlRoute,
  ServicesAudioVisualRoute: ServicesAudioVisualRoute,
  ServicesBuildingManagementRoute: ServicesBuildingManagementRoute,
  ServicesCarParkingRoute: ServicesCarParkingRoute,
  ServicesCustomSolutionRoute: ServicesCustomSolutionRoute,
  ServicesFireAlarmRoute: ServicesFireAlarmRoute,
  ServicesIntrusionSystemRoute: ServicesIntrusionSystemRoute,
  ServicesLeakDetectionRoute: ServicesLeakDetectionRoute,
  ServicesPublicAddressRoute: ServicesPublicAddressRoute,
  ServicesRoomControlRoute: ServicesRoomControlRoute,
  ServicesSurveillanceRoute: ServicesSurveillanceRoute,
  ServicesVesdaRoute: ServicesVesdaRoute,
  AboutIndexRoute: AboutIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
